"use client";

import Article from "@/components/Article";
import Unavailable from "@/components/Unavailable";
import { Editor } from "novel";
import { useState } from "react";

export default function Home() {
  const [content, setContent] = useState<any>({
    "type": "doc",
    "content": [
      {
        "type": "heading",
        "attrs": {
          "level": 1
        },
        "content": [
          {
            "type": "text",
            "marks": [
              {
                "type": "bold"
              }
            ],
            "text": "The Physics of the Sun"
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "The sun, the central star of our solar system, is a fascinating subject of study in the field of physics. Its immense gravitational pull and the complex processes happening within it have captivated scientists for centuries."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "At its core, the sun is a giant nuclear fusion reactor. Hydrogen atoms in the sun's core undergo fusion, combining to form helium and releasing an incredible amount of energy in the process. This process, known as nuclear fusion, powers the sun and generates the heat and light that sustain life on Earth."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "The sun's immense gravity plays a crucial role in holding our solar system together. It exerts a gravitational force that keeps all the planets, including Earth, in their respective orbits. This force of gravity also causes the sun's structure to be in a constant state of equilibrium, with the inward gravitational pull balanced by the outward pressure from nuclear fusion reactions."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Solar phenomena such as sunspots, solar flares, and the solar wind are all consequences of the sun's complex magnetic field. The sun's magnetic field is generated by the motion of charged particles within its core and outer layers. This magnetic activity has a profound impact on space weather and can affect satellite communications and power grids on Earth."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Understanding the physics of the sun is essential for predicting solar behavior, studying the origin of solar energy, and exploring the possibility of harnessing fusion power as a clean and sustainable energy source. As scientists continue to delve into the mysteries of the sun, we gain valuable insights into the fundamental principles of physics that govern our universe."
          }
        ]
      },
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Guillaume Duhan"
          }
        ]
      }
    ]
  })

  return <div className="w-full">
    <div className="my-12 container mx-auto max-w-[800px]">
      <Unavailable />
      {/* {content && <Article content={content} />}
      <Editor
        defaultValue={content}
        onUpdate={(editor?: any) => setContent(editor.getJSON())}
      /> */}
    </div>
  </div>
}
